
int bitNand(int, int);
int test_bitNand(int, int);
int isEqualThree(int, int, int);
int test_isEqualThree(int, int, int);
int swap30(int);
int test_swap30(int);
int logicalByteAdd(int, int);
int test_logicalByteAdd(int, int);
int rotateNibbleLeft(int, int);
int test_rotateNibbleLeft(int, int);
int bitBurstSize(int);
int test_bitBurstSize(int);
int isNegatable(int);
int test_isNegatable(int);
int sign(int);
int test_sign(int);
int maxOfThree(int, int, int);
int test_maxOfThree(int, int, int);
int isInRange(int);
int test_isInRange(int);
int ezThreeSixteenths(int);
int test_ezThreeSixteenths(int);
int sm2tc(int);
int test_sm2tc(int);
int binarySize(int);
int test_binarySize(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
unsigned float_exp(unsigned);
unsigned test_float_exp(unsigned);
unsigned float_half_denorm(unsigned);
unsigned test_float_half_denorm(unsigned);
